### PR TITLE
Adds support for PHP 8

### PR DESCRIPTION
**Pull request by emielmolenaar**
## PR Type

What kind of pull request is this? Put an `x` in all the boxes that apply:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Extend feature (non-breaking change which extends existing functionality)
- [ ] Change feature (non-breaking change which either changes or refactors existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## What does it change?

Adds support for PHP 8.

## Why this PR?

Adds support for PHP 8.

## How has this been tested?

By running the tests on PHP 8.0.5.

### CODE REVIEW

**Comment by emielmolenaar** [comment]
Tests are fixed. Might move to Github actions in the future as Travis is shutting down very soon 😃

**Comment by emielmolenaar** [comment]
@sebastiaanluca It would be great if you could merge and tag this 😄 !

**Comment by sebastiaanluca** [comment]
> @sebastiaanluca It would be great if you could merge and tag this 😄 !

My notifications for watched repositories were off, so I didn't get any emails about the issues and PRs 😬  Just got one because you mentioned me.

I'll try to merge all PRs and update its requirements today. I'll probably archive this package soon though. The code feels a bit hacky and I have no time to maintain it anymore. You're free to fork and maintain it of course.

**Comment by emielmolenaar** [comment]
All right, thanks!

**Pull request merged**
